# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameName',
            new_name='name',
        ),
    ]
