# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170508_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='gameName',
        ),
    ]
