# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gameuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='gameLocation',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gameName',
        ),
        migrations.AddField(
            model_name='game',
            name='gameAddress',
            field=models.CharField(default='Fake Address', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='gameCity',
            field=models.CharField(default='Jersey City', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='gameState',
            field=models.CharField(default='NJ', max_length=2),
        ),
        migrations.AddField(
            model_name='game',
            name='gameVenue',
            field=models.CharField(default='A Fake Park', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='gameZip',
            field=models.CharField(default='07302', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameType',
            field=models.CharField(default='Basketball', max_length=50),
        ),
    ]
