# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170512_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='isOrganizer',
            field=models.BooleanField(default=0),
        ),
    ]
