# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_gameuser_isorganizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
