# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170516_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuser',
            name='isOrganizer',
        ),
        migrations.AddField(
            model_name='gameuser',
            name='organizerId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_list', to='api.Game'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
