# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170516_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameuser',
            old_name='organizerId',
            new_name='organizer',
        ),
    ]
