# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 22:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170516_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameOrganizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
