# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170516_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameOrganizer',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
