# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170516_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameOrganizerId',
            field=models.IntegerField(default=11),
        ),
    ]
