# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_auto_20170517_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='game',
            name='gameOrganizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='gameuser',
            unique_together=set([('game', 'user')]),
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
